name: Save mdx data on firebase db

on:
    push:
        # branches:
        #     - gh-pages
        paths:
            - "**/*.mdx"

jobs:
    save_to_firebase:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v38
              with:
                  files_yaml: |
                      quiz:
                        - '**/*.mdx'
            - name: List all changed files
              run: |
                  for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                    echo "$file was changed"
                  done
