name: Push MDX Filenames to Firebase

on:
    push:
        paths:
            - "**/*.mdx"
        branches:
            - "lab2"

jobs:
    push_to_firebase:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v38

            - name: List all changed files
              run: |
                  for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                    echo "$file was changed"
                  done
