name: Main Workflow

on:
    push:
        branches:
            - master

jobs:
    run_workflows:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn

            - name: Test
              run: yarn test

            - name: Build
              run: yarn build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: ./public

            - name: Configure Firebase credentials
              env:
                  FIREBASE_CERTIFICATION: ${{ secrets.FIREBASE_CERTIFICATION }}
                  FIREBASE_DB_PATH: ${{ secrets.FIREBASE_DB_PATH }}
              run: |
                  echo "$FIREBASE_CERTIFICATION" > null_firebase_auth.json
                  node .github/scripts/firebase.js
