name: Main Workflow

on:
    push:

jobs:
    run_workflows:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: lab3

            # - name: Set up Node.js
            #   uses: actions/setup-node@v2
            #   with:
            #       node-version: 18
            # - name: Install dependencies
            #   run: yarn

            - name: Configure Firebase credentials
              env:
                  FIREBASE_CERTIFICATION_PATH: ${{ secrets.FIREBASE_CERTIFICATION_PATH }}
                  FIREBASE_DB_PATH: ${{ secrets.FIREBASE_DB_PATH }}
                  TEST: ${{ secrets.TEST }}
                  ppp: 123111
              run: |
                  echo "$FIREBASE_CERTIFICATION" > null_firebase_auth.json
                  node .github/scripts/firebase.js
