name: Main Workflow

on:
    push:

jobs:
    run_workflows:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: lab3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: Install dependencies
              run: yarn

            - name: Create credential json file
              run: |
                  credential='{"type": "service_account", "project_id": "null-2e3e5", "private_key_id": "'${{ secrets.private_key_id }}'", "client_email": "'${{ secrets.client_email }}'", "client_id": "'${{ secrets.client_id }}'", "universe_domain": "googleapis.com", "auth_uri": "'${{ secrets.auth_uri }}'", "token_uri": "'${{ secrets.token_uri }}'", "auth_provider_x509_cert_url": "'${{ secrets.auth_provider_x509_cert_url }}'", "client_x509_cert_url": "'${{ secrets.client_x509_cert_url }}'"}'
                  echo "$credential" > credential.json

            - name: Create dotenv
              env:
                  FIREBASE_CERTIFICATION_PATH=${{ secrets.FIREBASE_CERTIFICATION_PATH }}
                  FIREBASE_DB_PATH=${{ secrets.FIREBASE_DB_PATH }}
              run: |
                  echo "FIREBASE_CERTIFICATION_PATH=$FIREBASE_CERTIFICATION_PATH" >> .env
                  echo "FIREBASE_DB_PATH=$FIREBASE_DB_PATH" >> .env
                  echo "test=aaaa" >> .env

            - name: Configure Firebase credentials
              run: |
                  echo "$FIREBASE_CERTIFICATION" > null_firebase_auth.json
                  node .github/scripts/firebase.js
